// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: Asr.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// 音频帧状态枚举
enum Asr_FrameState: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case unspecified // = 0
  case first // = 1
  case middle // = 3
  case last // = 9
  case UNRECOGNIZED(Int)

  init() {
    self = .unspecified
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .first
    case 3: self = .middle
    case 9: self = .last
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .first: return 1
    case .middle: return 3
    case .last: return 9
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Asr_FrameState] = [
    .unspecified,
    .first,
    .middle,
    .last,
  ]

}

/// ASR WebSocket 请求消息
/// 用于 StartTask, StartSession, FinishSession, TaskRequest 等操作
struct Asr_AsrRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 认证 token (从 Settings API 获取的 app_key)
  var token: String = String()

  /// 服务名称，固定为 "ASR"
  var serviceName: String = String()

  /// 方法名称
  /// - "StartTask": 启动任务
  /// - "StartSession": 启动会话
  /// - "FinishSession": 结束会话
  /// - "TaskRequest": 发送音频数据
  var methodName: String = String()

  /// JSON 格式的负载数据
  /// - StartSession: 会话配置 (audio_info, enable_punctuation 等)
  /// - TaskRequest: 元数据 {"extra": {}, "timestamp_ms": xxx}
  var payload: String = String()

  /// 音频数据 (仅 TaskRequest 使用)
  var audioData: Data = Data()

  /// 请求 ID (UUID)
  var requestID: String = String()

  /// 帧状态 (仅 TaskRequest 使用)
  var frameState: Asr_FrameState = .unspecified

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// ASR WebSocket 响应消息
struct Asr_AsrResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 请求 ID
  var requestID: String = String()

  /// 任务 ID
  var taskID: String = String()

  /// 服务名称
  var serviceName: String = String()

  /// 消息类型
  /// - "TaskStarted": 任务已启动
  /// - "SessionStarted": 会话已启动
  /// - "TaskFailed": 任务失败
  /// - "SessionFailed": 会话失败
  /// - "SessionFinished": 会话结束
  var messageType: String = String()

  /// 状态码
  var statusCode: Int32 = 0

  /// 状态消息 (如 "OK")
  var statusMessage: String = String()

  /// JSON 格式的识别结果
  /// {"results": [...], "extra": {...}}
  var resultJson: String = String()

  /// 不知道是干啥的。。。
  var unknownField9: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "asr"

extension Asr_FrameState: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0FRAME_STATE_UNSPECIFIED\0\u{1}FRAME_STATE_FIRST\0\u{2}\u{2}FRAME_STATE_MIDDLE\0\u{2}\u{6}FRAME_STATE_LAST\0")
}

extension Asr_AsrRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AsrRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{2}token\0\u{3}service_name\0\u{4}\u{2}method_name\0\u{1}payload\0\u{3}audio_data\0\u{3}request_id\0\u{3}frame_state\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try { try decoder.decodeSingularStringField(value: &self.token) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.serviceName) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.methodName) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.payload) }()
      case 7: try { try decoder.decodeSingularBytesField(value: &self.audioData) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.requestID) }()
      case 9: try { try decoder.decodeSingularEnumField(value: &self.frameState) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.token.isEmpty {
      try visitor.visitSingularStringField(value: self.token, fieldNumber: 2)
    }
    if !self.serviceName.isEmpty {
      try visitor.visitSingularStringField(value: self.serviceName, fieldNumber: 3)
    }
    if !self.methodName.isEmpty {
      try visitor.visitSingularStringField(value: self.methodName, fieldNumber: 5)
    }
    if !self.payload.isEmpty {
      try visitor.visitSingularStringField(value: self.payload, fieldNumber: 6)
    }
    if !self.audioData.isEmpty {
      try visitor.visitSingularBytesField(value: self.audioData, fieldNumber: 7)
    }
    if !self.requestID.isEmpty {
      try visitor.visitSingularStringField(value: self.requestID, fieldNumber: 8)
    }
    if self.frameState != .unspecified {
      try visitor.visitSingularEnumField(value: self.frameState, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Asr_AsrRequest, rhs: Asr_AsrRequest) -> Bool {
    if lhs.token != rhs.token {return false}
    if lhs.serviceName != rhs.serviceName {return false}
    if lhs.methodName != rhs.methodName {return false}
    if lhs.payload != rhs.payload {return false}
    if lhs.audioData != rhs.audioData {return false}
    if lhs.requestID != rhs.requestID {return false}
    if lhs.frameState != rhs.frameState {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Asr_AsrResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AsrResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}request_id\0\u{3}task_id\0\u{3}service_name\0\u{3}message_type\0\u{3}status_code\0\u{3}status_message\0\u{3}result_json\0\u{4}\u{2}unknown_field_9\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.taskID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.serviceName) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.messageType) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.statusCode) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.statusMessage) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.resultJson) }()
      case 9: try { try decoder.decodeSingularInt32Field(value: &self.unknownField9) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.requestID.isEmpty {
      try visitor.visitSingularStringField(value: self.requestID, fieldNumber: 1)
    }
    if !self.taskID.isEmpty {
      try visitor.visitSingularStringField(value: self.taskID, fieldNumber: 2)
    }
    if !self.serviceName.isEmpty {
      try visitor.visitSingularStringField(value: self.serviceName, fieldNumber: 3)
    }
    if !self.messageType.isEmpty {
      try visitor.visitSingularStringField(value: self.messageType, fieldNumber: 4)
    }
    if self.statusCode != 0 {
      try visitor.visitSingularInt32Field(value: self.statusCode, fieldNumber: 5)
    }
    if !self.statusMessage.isEmpty {
      try visitor.visitSingularStringField(value: self.statusMessage, fieldNumber: 6)
    }
    if !self.resultJson.isEmpty {
      try visitor.visitSingularStringField(value: self.resultJson, fieldNumber: 7)
    }
    if self.unknownField9 != 0 {
      try visitor.visitSingularInt32Field(value: self.unknownField9, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Asr_AsrResponse, rhs: Asr_AsrResponse) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.taskID != rhs.taskID {return false}
    if lhs.serviceName != rhs.serviceName {return false}
    if lhs.messageType != rhs.messageType {return false}
    if lhs.statusCode != rhs.statusCode {return false}
    if lhs.statusMessage != rhs.statusMessage {return false}
    if lhs.resultJson != rhs.resultJson {return false}
    if lhs.unknownField9 != rhs.unknownField9 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
